# Generated by Django 4.2.7 on 2023-11-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
